server:
  port: 80
spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: 101.37.253.142
      port: 8500
      discovery:
        # 向注册中心注册名字为cloud-payment-server的服务
        service-name: cloud-order-service
        # 开启心跳检查
        heartbeat:
          enabled: true
request:
  url: http://cloud-payment-server
