server:
  port: 80
spring:
  application:
    name: cloud-payment-order

eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
    # 不自动注册 也就是自己去检测服务
    fetchRegistry: true
    # 将自己注入到eureka中
    register-with-eureka: true


feign:
  httpclient:
    # 设置feign从eureka中读取可用服务的超时时间
    connection-timeout: 5000
ribbon:
  #设置ribbon的超时时间
  read-timeout: 5000
  # 设置ribbon从eureka中读取可用服务的超时时间
  ConnectTimeout: 5000