server:
  port: 8401

spring:
  application:
    name: nacos-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        sentinel 基本配置
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      log:
        dir: D:/logs/

management:
  endpoints:
    web:
      exposure:
        include: '*'