server:
  port: 8802

spring:
  application:
    name: spring-cloud-stream-8802
  rabbitmq:
    addresses: 101.37.253.142
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
      direct:
        prefetch: 5
    virtual-host: my_vhost
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              host: 101.37.253.142
              port: 5672
              username: admin
              password: admin
              virtual-host: my_vhost
      bindings:
          input:
            destination: studyExchange
            content-type: application/json
            binder: defaultRabbit
            group:  myxiaowangA


eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
    fetchRegistry: true
    register-with-eureka: true
  instance:
    # 向注册中心提供别名
    instance-id: spring-cloud-stream-8802
    # 向注册中心暴露ip
    prefer-ip-address: true
    # 向注册发送心跳机制的时间
    lease-renewal-interval-in-seconds: 60
    # 最后一次心跳间隔多久 会触发注销
    lease-expiration-duration-in-seconds: 90