server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server:7002

eureka:
  instance:
    hostname: eureka7002
  client:
    # 不注册自己
    register-with-eureka: false
    # 不自动注册 也就是自己去检测服务
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka
