server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server:7001

eureka:
  instance:
    hostname: eureka7001
  client:
    # 不注册自己
    register-with-eureka: false
    # 不自动注册 也就是自己去检测服务
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7002:7002/eureka
  server:
    # 容错机制的关闭
    enable-self-preservation: false
    # 超时断开连接
    eviction-interval-timer-in-ms: 2000