server:
  port: 9527
spring:
  application:
    name: cloud-getaway


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CLOUD-PAYMENT-SERVER
          # gateway 网关自带负载均衡的功能
          uri: lb://CLOUD-PAYMENT-SERVER
          predicates:
            - Path=/payment/findById/**
# 使用配置的方式来配置断言地址 会导致这个配置文件非常大
# 使用代码的方式完成配置 请看GatewayRoutingConfig
#        - id: CLOUD-PAYMENT-HYSTRIX-ORDER  #往注册网关注册的服务
#          uri: http://localhost:80  #服务的地址
#          predicates:
#            - Path=/order/findById/** #gateway的断言地址



eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
    fetchRegistry: true
    register-with-eureka: true
  instance:
    # 向注册中心提供别名
    instance-id: cloud-gatewat-server9527
    # 向注册中心暴露ip
    prefer-ip-address: true
    # 向注册发送心跳机制的时间
    lease-renewal-interval-in-seconds: 60
    # 最后一次心跳间隔多久 会触发注销
    lease-expiration-duration-in-seconds: 90
