server:
  port: 80
spring:
  application:
    name: cloud-payment-order

eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
    # 不自动注册 也就是自己去检测服务
    fetchRegistry: true
    # 将自己注入到eureka中
    register-with-eureka: true

request:
  url: http://CLOUD-PAYMENT-SERVER