server:
  port: 80
spring:
  application:
    name: cloud-payment-hystrix-order

eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
    # 不自动注册 也就是自己去检测服务
    fetchRegistry: true
    # 将自己注入到eureka中
    register-with-eureka: true


 #Hystirx 请求超时通用返回时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 300000